const data = {
  products: [
    {
      name: 'book1',
      slug: 'book1',
      category: 'uponnas',
      image: '/images/book9.png',
      price: 120,
      countInStock: 10,
      brand: 'books',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality book',
    },
    {
      name: 'book2',
      slug: 'book2',
      category: 'uponnas',
      image: '/images/book9.png',
      price: 120,
      countInStock: 10,
      brand: 'books',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality book',
    },
    {
      name: 'book3',
      slug: 'book3',
      category: 'uponnas',
      image: '/images/book9.png',
      price: 120,
      countInStock: 10,
      brand: 'books',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality book',
    },
    {
      name: 'book4',
      slug: 'book4',
      category: 'uponnas',
      image: '/images/book9.png',
      price: 120,
      countInStock: 10,
      brand: 'books',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality book',
    },
  ],
};

export default data;
